"""Shared request and response models."""

from typing import Literal

from pydantic import BaseModel, Field, field_validator


class ResearchRequest(BaseModel):
    """Validated agent request."""

    query: str = Field(..., min_length=5, max_length=500)
    context: str | None = Field(default=None, max_length=2000)
    audience: str = Field(default="general", min_length=3, max_length=100)
    output_format: Literal["markdown", "text"] = "markdown"
    max_sections: int = Field(default=4, ge=1, le=8)

    @field_validator("query")
    @classmethod
    def normalize_query(cls, value: str) -> str:
        cleaned = " ".join(value.split())
        if not cleaned.endswith("?"):
            return cleaned
        return cleaned

    @field_validator("context")
    @classmethod
    def normalize_context(cls, value: str | None) -> str | None:
        if value is None:
            return value
        cleaned = value.strip()
        return cleaned or None


class ResearchSection(BaseModel):
    """A section generated by the agent."""

    heading: str = Field(..., min_length=3, max_length=120)
    content: str = Field(..., min_length=20)


class ResearchResponse(BaseModel):
    """Structured agent output."""

    original_query: str
    refined_goal: str
    sections: list[ResearchSection]
    summary: str = Field(..., min_length=20)
    execution_mode: Literal["live_llm", "template_fallback"]
